-- Level Up schema for Tiger Data (PostgreSQL + TimescaleDB).
-- Apply with: npm run db:schema   (safe to re-run; {{TZ}} is replaced with APP_TIMEZONE)
-- Statements run one at a time, outside a transaction, because continuous aggregates require it.

-- ---------- relational data ----------

CREATE TABLE IF NOT EXISTS users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth0_id        text NOT NULL UNIQUE,
  name            text NOT NULL DEFAULT 'Player',
  onboarded       boolean NOT NULL DEFAULT false,
  chosen          text[] NOT NULL DEFAULT '{}',
  look            jsonb NOT NULL DEFAULT '{}',
  answers         jsonb NOT NULL DEFAULT '{}',
  level           int NOT NULL DEFAULT 1 CHECK (level >= 1),
  xp              int NOT NULL DEFAULT 0 CHECK (xp >= 0),
  coins           int NOT NULL DEFAULT 50 CHECK (coins >= 0),
  materials       jsonb NOT NULL DEFAULT '{}',
  stats           jsonb NOT NULL DEFAULT '{}',
  items           jsonb NOT NULL DEFAULT '{}',
  quests_done     int NOT NULL DEFAULT 0,
  failed_days_in_row int NOT NULL DEFAULT 0,
  rift            jsonb,
  game_date       date NOT NULL,
  extra_today     int NOT NULL DEFAULT 0,
  gate_won_on     date,
  started         date NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS category_progress (
  user_id   bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category  text NOT NULL,
  count     int NOT NULL DEFAULT 0 CHECK (count >= 0),
  target    int NOT NULL DEFAULT 10,
  PRIMARY KEY (user_id, category)
);

CREATE TABLE IF NOT EXISTS quests (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date             date NOT NULL,
  category         text NOT NULL,
  kind             text NOT NULL CHECK (kind IN ('required', 'bonus', 'extra')),
  position         int NOT NULL,
  title            text NOT NULL,
  description      text,
  duration_minutes int NOT NULL CHECK (duration_minutes BETWEEN 1 AND 240),
  proof            text NOT NULL CHECK (proof IN ('VITALS', 'FOCUS', 'PHOTO', 'HONOR')),
  status           text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'completed', 'failed')),
  started_at       timestamptz,
  ends_at          timestamptz,
  completed_at     timestamptz,
  rewards          jsonb,
  proof_result     jsonb NOT NULL DEFAULT '{}',
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, date, category)
);
CREATE INDEX IF NOT EXISTS quests_user_date ON quests (user_id, date);

CREATE TABLE IF NOT EXISTS story_chapters (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          text NOT NULL CHECK (type IN ('intro', 'rankUp', 'banished', 'returned')),
  title         text NOT NULL,
  text          text NOT NULL,
  audio_url     text,
  audio_status  text NOT NULL DEFAULT 'pending' CHECK (audio_status IN ('pending', 'ready', 'failed', 'none')),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS story_user_created ON story_chapters (user_id, created_at DESC);

-- ---------- time-series data (hypertables) ----------

-- One row per second of a VITALS or FOCUS quest (heart rate from Presage, breathing, focus score).
CREATE TABLE IF NOT EXISTS vitals_readings (
  time            timestamptz NOT NULL,
  user_id         bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  quest_id        bigint NOT NULL,
  bpm             smallint CHECK (bpm BETWEEN 25 AND 250),
  breathing_rate  real CHECK (breathing_rate BETWEEN 0 AND 80),
  focus_score     real CHECK (focus_score BETWEEN 0 AND 1)
);
SELECT create_hypertable('vitals_readings', by_range('time', INTERVAL '7 days'), if_not_exists => true);
CREATE UNIQUE INDEX IF NOT EXISTS vitals_quest_time ON vitals_readings (quest_id, time);

-- Everything that changes a player's progress: the source for daily stats and the history calendar.
CREATE TABLE IF NOT EXISTS player_events (
  time      timestamptz NOT NULL DEFAULT now(),
  user_id   bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type      text NOT NULL CHECK (type IN ('quest_completed', 'day_closed', 'rift', 'purchase', 'gate_win', 'level_up')),
  category  text,
  proof     text,
  xp        int NOT NULL DEFAULT 0,
  coins     int NOT NULL DEFAULT 0,
  result    text CHECK (result IN ('cleared', 'partial', 'missed')),
  data      jsonb
);
SELECT create_hypertable('player_events', by_range('time', INTERVAL '30 days'), if_not_exists => true);
CREATE INDEX IF NOT EXISTS player_events_user_time ON player_events (user_id, time DESC);

-- ---------- continuous aggregates (kept up to date by the database) ----------

CREATE MATERIALIZED VIEW IF NOT EXISTS daily_player_stats
WITH (timescaledb.continuous, timescaledb.materialized_only = false) AS
SELECT time_bucket('1 day', time, '{{TZ}}') AS day,
  user_id,
  count(*) FILTER (WHERE type = 'quest_completed') AS quests,
  sum(xp) AS xp,
  sum(coins) AS coins,
  count(*) FILTER (WHERE type = 'quest_completed' AND proof = 'VITALS') AS vitals_quests,
  count(*) FILTER (WHERE type = 'quest_completed' AND proof = 'FOCUS')  AS focus_quests,
  count(*) FILTER (WHERE type = 'quest_completed' AND proof = 'PHOTO')  AS photo_quests,
  count(*) FILTER (WHERE type = 'quest_completed' AND proof = 'HONOR')  AS honor_quests,
  max(result) FILTER (WHERE type = 'day_closed') AS day_result
FROM player_events
GROUP BY day, user_id
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS vitals_per_minute
WITH (timescaledb.continuous, timescaledb.materialized_only = false) AS
SELECT time_bucket('1 minute', time) AS minute,
  user_id,
  quest_id,
  avg(bpm) AS avg_bpm,
  min(bpm) AS min_bpm,
  max(bpm) AS max_bpm,
  avg(breathing_rate) AS avg_breathing,
  avg(focus_score) AS avg_focus,
  count(*) AS samples
FROM vitals_readings
GROUP BY minute, user_id, quest_id
WITH NO DATA;

SELECT add_continuous_aggregate_policy('daily_player_stats',
  start_offset => INTERVAL '3 days', end_offset => INTERVAL '1 hour',
  schedule_interval => INTERVAL '15 minutes', if_not_exists => true);

SELECT add_continuous_aggregate_policy('vitals_per_minute',
  start_offset => INTERVAL '1 day', end_offset => INTERVAL '1 minute',
  schedule_interval => INTERVAL '5 minutes', if_not_exists => true);

-- ---------- compression and retention (keeps us inside the 750 MB free tier) ----------

DO $$
BEGIN
  IF NOT (SELECT compression_enabled FROM timescaledb_information.hypertables WHERE hypertable_name = 'vitals_readings') THEN
    ALTER TABLE vitals_readings SET (
      timescaledb.compress,
      timescaledb.compress_segmentby = 'user_id',
      timescaledb.compress_orderby = 'quest_id, time'
    );
  END IF;
  IF NOT (SELECT compression_enabled FROM timescaledb_information.hypertables WHERE hypertable_name = 'player_events') THEN
    ALTER TABLE player_events SET (
      timescaledb.compress,
      timescaledb.compress_segmentby = 'user_id',
      timescaledb.compress_orderby = 'time DESC'
    );
  END IF;
END
$$;

SELECT add_compression_policy('vitals_readings', INTERVAL '3 days', if_not_exists => true);
SELECT add_compression_policy('player_events', INTERVAL '30 days', if_not_exists => true);

-- Raw per-second readings go after 90 days; vitals_per_minute keeps the history.
SELECT add_retention_policy('vitals_readings', INTERVAL '90 days', if_not_exists => true);
